// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGameTracker.Data;

#nullable disable

namespace VideoGameTracker.Migrations
{
    [DbContext(typeof(VideoGameTrackerDbContext))]
    [Migration("20260510135804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("GameGenres", b =>
                {
                    b.Property<int>("GamesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenresId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GamesId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("GameGenres");

                    b.HasData(
                        new
                        {
                            GamesId = 1,
                            GenresId = 1
                        },
                        new
                        {
                            GamesId = 1,
                            GenresId = 2
                        },
                        new
                        {
                            GamesId = 1,
                            GenresId = 4
                        },
                        new
                        {
                            GamesId = 2,
                            GenresId = 1
                        },
                        new
                        {
                            GamesId = 2,
                            GenresId = 2
                        },
                        new
                        {
                            GamesId = 3,
                            GenresId = 1
                        },
                        new
                        {
                            GamesId = 3,
                            GenresId = 2
                        },
                        new
                        {
                            GamesId = 4,
                            GenresId = 2
                        },
                        new
                        {
                            GamesId = 4,
                            GenresId = 4
                        },
                        new
                        {
                            GamesId = 5,
                            GenresId = 2
                        },
                        new
                        {
                            GamesId = 5,
                            GenresId = 4
                        },
                        new
                        {
                            GamesId = 6,
                            GenresId = 2
                        },
                        new
                        {
                            GamesId = 7,
                            GenresId = 3
                        },
                        new
                        {
                            GamesId = 7,
                            GenresId = 2
                        },
                        new
                        {
                            GamesId = 8,
                            GenresId = 3
                        },
                        new
                        {
                            GamesId = 9,
                            GenresId = 3
                        },
                        new
                        {
                            GamesId = 9,
                            GenresId = 2
                        });
                });

            modelBuilder.Entity("GamePlatforms", b =>
                {
                    b.Property<int>("GamesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlatformsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GamesId", "PlatformsId");

                    b.HasIndex("PlatformsId");

                    b.ToTable("GamePlatforms");

                    b.HasData(
                        new
                        {
                            GamesId = 1,
                            PlatformsId = 1
                        },
                        new
                        {
                            GamesId = 1,
                            PlatformsId = 2
                        },
                        new
                        {
                            GamesId = 1,
                            PlatformsId = 3
                        },
                        new
                        {
                            GamesId = 2,
                            PlatformsId = 1
                        },
                        new
                        {
                            GamesId = 2,
                            PlatformsId = 2
                        },
                        new
                        {
                            GamesId = 2,
                            PlatformsId = 3
                        },
                        new
                        {
                            GamesId = 3,
                            PlatformsId = 1
                        },
                        new
                        {
                            GamesId = 4,
                            PlatformsId = 1
                        },
                        new
                        {
                            GamesId = 4,
                            PlatformsId = 2
                        },
                        new
                        {
                            GamesId = 4,
                            PlatformsId = 3
                        },
                        new
                        {
                            GamesId = 5,
                            PlatformsId = 1
                        },
                        new
                        {
                            GamesId = 5,
                            PlatformsId = 2
                        },
                        new
                        {
                            GamesId = 5,
                            PlatformsId = 3
                        },
                        new
                        {
                            GamesId = 6,
                            PlatformsId = 1
                        },
                        new
                        {
                            GamesId = 6,
                            PlatformsId = 3
                        },
                        new
                        {
                            GamesId = 7,
                            PlatformsId = 1
                        },
                        new
                        {
                            GamesId = 8,
                            PlatformsId = 1
                        },
                        new
                        {
                            GamesId = 9,
                            PlatformsId = 1
                        });
                });

            modelBuilder.Entity("VideoGameTracker.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Founded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Poland",
                            Description = "Polish video game developer known for The Witcher series",
                            Founded = new DateTime(2002, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CD Projekt Red"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            Description = "American video game developer and publisher known for GTA series",
                            Founded = new DateTime(1998, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rockstar Games"
                        },
                        new
                        {
                            Id = 3,
                            Country = "USA",
                            Description = "Developer of legendary fps games and Half-Life series",
                            Founded = new DateTime(1996, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Valve Corporation"
                        });
                });

            modelBuilder.Entity("VideoGameTracker.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AverageRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 95,
                            Description = "Open-world RPG with rich storytelling and complex characters",
                            DeveloperId = 1,
                            ReleaseYear = 2015,
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 77,
                            Description = "Futuristic action RPG set in Night City",
                            DeveloperId = 1,
                            ReleaseYear = 2020,
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 3,
                            AverageRating = 88,
                            Description = "Predecessor to The Witcher 3",
                            DeveloperId = 1,
                            ReleaseYear = 2011,
                            Title = "The Witcher 2: Assassins of Kings"
                        },
                        new
                        {
                            Id = 4,
                            AverageRating = 97,
                            Description = "Open-world action game set in Los Santos",
                            DeveloperId = 2,
                            ReleaseYear = 2013,
                            Title = "Grand Theft Auto V"
                        },
                        new
                        {
                            Id = 5,
                            AverageRating = 97,
                            Description = "Western action-adventure game",
                            DeveloperId = 2,
                            ReleaseYear = 2018,
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 6,
                            AverageRating = 94,
                            Description = "Action game set in Liberty City",
                            DeveloperId = 2,
                            ReleaseYear = 2008,
                            Title = "GTA IV"
                        },
                        new
                        {
                            Id = 7,
                            AverageRating = 96,
                            Description = "Revolutionary first-person shooter",
                            DeveloperId = 3,
                            ReleaseYear = 2004,
                            Title = "Half-Life 2"
                        },
                        new
                        {
                            Id = 8,
                            AverageRating = 82,
                            Description = "Competitive team-based FPS",
                            DeveloperId = 3,
                            ReleaseYear = 2023,
                            Title = "Counter-Strike 2"
                        },
                        new
                        {
                            Id = 9,
                            AverageRating = 93,
                            Description = "VR prequel to Half-Life 2",
                            DeveloperId = 3,
                            ReleaseYear = 2020,
                            Title = "Half-Life: Alyx"
                        });
                });

            modelBuilder.Entity("VideoGameTracker.Models.GameEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoursPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewComment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReviewScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("GameEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            HoursPlayed = 150,
                            ReviewComment = "Amazing game, incredible story and characters!",
                            ReviewScore = 95,
                            Status = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            HoursPlayed = 200,
                            ReviewComment = "Best RPG I've ever played!",
                            ReviewScore = 98,
                            Status = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 4,
                            HoursPlayed = 80,
                            ReviewComment = "Great open-world gameplay",
                            ReviewScore = 90,
                            Status = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 8,
                            HoursPlayed = 45,
                            ReviewComment = "Competitive and fun",
                            ReviewScore = 85,
                            Status = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 2,
                            HoursPlayed = 120,
                            ReviewComment = "Good game, but buggy at launch",
                            ReviewScore = 75,
                            Status = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 5,
                            HoursPlayed = 180,
                            ReviewComment = "Outstanding story and immersion",
                            ReviewScore = 96,
                            Status = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 7,
                            HoursPlayed = 0,
                            Status = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 3,
                            HoursPlayed = 95,
                            Status = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("VideoGameTracker.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Games with character progression and storytelling",
                            Name = "Role-Playing Game"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fast-paced action-oriented games",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fast shooter games played from first-person perspective",
                            Name = "First-Person Shooter"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Adventure and exploration games",
                            Name = "Adventure"
                        });
                });

            modelBuilder.Entity("VideoGameTracker.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PC",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "PlayStation 5",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Xbox Series X",
                            Type = 2
                        });
                });

            modelBuilder.Entity("VideoGameTracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "gamerpro@email.com",
                            Password = "hashed_password_1",
                            RegisteredAt = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "GamerPro"
                        },
                        new
                        {
                            Id = 2,
                            Email = "rpgfan@email.com",
                            Password = "hashed_password_2",
                            RegisteredAt = new DateTime(2021, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "RPGFanatic"
                        },
                        new
                        {
                            Id = 3,
                            Email = "actionjunkie@email.com",
                            Password = "hashed_password_3",
                            RegisteredAt = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "ActionJunkie"
                        });
                });

            modelBuilder.Entity("GameGenres", b =>
                {
                    b.HasOne("VideoGameTracker.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoGameTracker.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamePlatforms", b =>
                {
                    b.HasOne("VideoGameTracker.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoGameTracker.Models.Platform", null)
                        .WithMany()
                        .HasForeignKey("PlatformsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VideoGameTracker.Models.Game", b =>
                {
                    b.HasOne("VideoGameTracker.Models.Developer", "Developer")
                        .WithMany("Games")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("VideoGameTracker.Models.GameEntry", b =>
                {
                    b.HasOne("VideoGameTracker.Models.Game", "Game")
                        .WithMany("GameEntries")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoGameTracker.Models.User", "User")
                        .WithMany("GameEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VideoGameTracker.Models.Developer", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("VideoGameTracker.Models.Game", b =>
                {
                    b.Navigation("GameEntries");
                });

            modelBuilder.Entity("VideoGameTracker.Models.User", b =>
                {
                    b.Navigation("GameEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
